# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.pca_spca_bigmatrix <- function(xpMat, center = TRUE, scale = FALSE, ncomp = -1L, block_size = 2048L, max_iter = 50L, tol = 1e-4, return_scores = FALSE, verbose = FALSE) {
    .Call(`_bigPCAcpp_pca_spca_bigmatrix`, xpMat, center, scale, ncomp, block_size, max_iter, tol, return_scores, verbose)
}

.pca_bigmatrix <- function(xpMat, center = TRUE, scale = FALSE, ncomp = -1L, block_size = 1024L) {
    .Call(`_bigPCAcpp_pca_bigmatrix`, xpMat, center, scale, ncomp, block_size)
}

.svd_bigmatrix <- function(xpMat, nu = -1L, nv = -1L, block_size = 1024L, method = "dgesdd") {
    .Call(`_bigPCAcpp_svd_bigmatrix`, xpMat, nu, nv, block_size, method)
}

.pca_scores_bigmatrix <- function(xpMat, rotation, center, scale, ncomp = -1L, block_size = 1024L) {
    .Call(`_bigPCAcpp_pca_scores_bigmatrix`, xpMat, rotation, center, scale, ncomp, block_size)
}

.pca_variable_loadings <- function(rotation, sdev) {
    .Call(`_bigPCAcpp_pca_variable_loadings`, rotation, sdev)
}

.pca_variable_correlations <- function(rotation, sdev, column_sd, scaled_input) {
    .Call(`_bigPCAcpp_pca_variable_correlations`, rotation, sdev, column_sd, scaled_input)
}

.pca_variable_contributions <- function(loadings) {
    .Call(`_bigPCAcpp_pca_variable_contributions`, loadings)
}

.pca_individual_contributions <- function(scores, sdev, total_weight = NA_real_) {
    .Call(`_bigPCAcpp_pca_individual_contributions`, scores, sdev, total_weight)
}

.pca_individual_cos2 <- function(scores) {
    .Call(`_bigPCAcpp_pca_individual_cos2`, scores)
}

.pca_variable_cos2 <- function(correlations) {
    .Call(`_bigPCAcpp_pca_variable_cos2`, correlations)
}

.pca_spca_stream_bigmatrix <- function(xpMat, xpRotation, center = TRUE, scale = FALSE, ncomp = -1L, block_size = 2048L, max_iter = 50L, tol = 1e-4, return_scores = FALSE, verbose = FALSE) {
    .Call(`_bigPCAcpp_pca_spca_stream_bigmatrix`, xpMat, xpRotation, center, scale, ncomp, block_size, max_iter, tol, return_scores, verbose)
}

.pca_stream_bigmatrix <- function(xpMat, xpRotation, center = TRUE, scale = FALSE, ncomp = -1L, block_size = 1024L) {
    .Call(`_bigPCAcpp_pca_stream_bigmatrix`, xpMat, xpRotation, center, scale, ncomp, block_size)
}

.pca_scores_stream_bigmatrix <- function(xpMat, xpDest, rotation, center, scale, ncomp = -1L, block_size = 1024L) {
    .Call(`_bigPCAcpp_pca_scores_stream_bigmatrix`, xpMat, xpDest, rotation, center, scale, ncomp, block_size)
}

.pca_variable_loadings_stream_bigmatrix <- function(xpRotation, sdev, xpDest) {
    .Call(`_bigPCAcpp_pca_variable_loadings_stream_bigmatrix`, xpRotation, sdev, xpDest)
}

.pca_variable_correlations_stream_bigmatrix <- function(xpRotation, sdev, column_sd, scaled_input, xpDest) {
    .Call(`_bigPCAcpp_pca_variable_correlations_stream_bigmatrix`, xpRotation, sdev, column_sd, scaled_input, xpDest)
}

.pca_variable_contributions_stream_bigmatrix <- function(xpLoadings, xpDest) {
    .Call(`_bigPCAcpp_pca_variable_contributions_stream_bigmatrix`, xpLoadings, xpDest)
}

.svd_robust_cpp <- function(x, ncomp, max_iter, tol, huber_k) {
    .Call(`_bigPCAcpp_svd_robust_cpp`, x, ncomp, max_iter, tol, huber_k)
}

